# Generated by Django 3.2.4 on 2022-07-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0003_auto_20220711_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
