# Generated by Django 3.2.4 on 2022-07-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0004_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
