# Generated by Django 3.2.4 on 2022-07-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0006_auto_20220711_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_query_name='movies', through='moviedb.Role', to='moviedb.Actor'),
        ),
    ]
