# Generated by Django 3.2.4 on 2022-07-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0007_alter_movie_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(related_name='actors', through='moviedb.Role', to='moviedb.Movie'),
        ),
    ]
