# Generated by Django 3.2.4 on 2022-07-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0010_auto_20220712_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(through='moviedb.Role', to='moviedb.Movie'),
        ),
    ]
