# Generated by Django 3.2.4 on 2022-07-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0011_alter_actor_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(related_name='actors', through='moviedb.Role', to='moviedb.Movie'),
        ),
    ]
